[package]
name = "base_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"

# Platform
sdl2 = "0.34.5"
gl = "0.10.0"
glam = "0.23.0"

# ImGui
imgui = "0.9.0"
imgui-opengl-renderer = "0.12.0"
imgui-sdl2 = "0.15.1"

# Logging
log = "0.4.17"
simple_logger = "4.1.0"

# Serialization
configparser = "3.0.2"

# Application Icon
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
