[package]
name = "base_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5" # this version must match the version of sdl2 used by imgui-sdl2-support
gl = "0.10.0"

# ImGui
imgui = "0.9.0"
imgui-opengl-renderer = "0.12.0"
imgui-sdl2 = "0.15.1"

# Logging
log = "0.4.17"
simple_logger = "4.1.0"

# Serialization
configparser = "3.0.2"
